inputs_def:
  - handle: 工作路径
    description: Input
    json_schema:
      type: string
  - handle: 下载地址
    json_schema:
      type: string
  - handle: 后缀名
    json_schema:
      type: string
outputs_def:
  - handle: 下载路径
    description: Output
    json_schema:
      type: string
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
icon: ":skill-icons:typescript:"
